# Generated by Django 5.2.7 on 2025-10-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Отзыв',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_поста', models.DateTimeField(auto_now=True)),
                ('картинка', models.ImageField(upload_to='медиа')),
                ('текст', models.TextField()),
            ],
        ),
    ]
