# Generated by Django 5.2.7 on 2025-10-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('приложение', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='отзыв',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
