# Generated by Django 5.2.7 on 2025-10-31 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('приложение', '0004_аватарка'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='аватарка',
            options={'verbose_name': 'Аватарка', 'verbose_name_plural': 'Аватарки'},
        ),
        migrations.AlterField(
            model_name='аватарка',
            name='юзер',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
