# Generated by Django 5.2.7 on 2025-11-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('приложение', '0005_alter_аватарка_options_alter_аватарка_юзер'),
    ]

    operations = [
        migrations.CreateModel(
            name='Тег',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('текст', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ОтзывыТеги',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('отзыв', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='приложение.отзыв')),
                ('тег', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='приложение.тег')),
            ],
        ),
        migrations.AddField(
            model_name='отзыв',
            name='тег',
            field=models.ManyToManyField(blank=True, through='приложение.ОтзывыТеги', to='приложение.тег'),
        ),
    ]
